// ============================================================
// SPRITES — 16-bit style character sprites with shading
// Each sprite: { palette, width, height, frames[] }
// Frame = string rows, each char maps to palette color
// ============================================================

function buildSprite(def) {
  const compiled = [];
  for (const frame of def.frames) {
    const rows = frame.trim().split('\n').map(r => r.trimStart());
    compiled.push(rows);
  }
  return { palette: def.palette, w: def.w, h: def.h, frames: compiled };
}

const PALETTES = {
  // ----- ANGEL -----
  angel: buildSprite({
    w: 16, h: 22,
    palette: {
      '.': null,
      'K': '#1a0a2e', 'k': '#2a1a3e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'w': '#f4f4ff', 'W': '#c8c8e8', 'G': '#9898b8',
      'y': '#fff8a0', 'Y': '#ffd84d', 'o': '#e8a020',
      'f': '#e8f4ff', 'F': '#b0c8e0', 'g': '#88a0c0',
      'e': '#180830', 'r': '#ff7070', 'h': '#ffffff',
      'p': '#e0d0ff', 'P': '#b8a0e0',
    },
    frames: [
`
.......yYy......
......YoYoY.....
.......yYy......
......KssK......
.....KseSesK....
.....KsrSrsK....
......KsSsK.....
...f..KwwwK..f..
..fF.KwWhwWK.Ff.
..fF.KWGwGWK.Ff.
..fg.KwWhwWK.gf.
..f..KWwwwWK..f.
.....KWGGwK.....
......KwwK......
......KwwK......
.....KxKKxK.....
.....Kx..xK.....
......K..K......
`,
`
.......yYy......
......YoYoY.....
.......yYy......
......KssK......
.....KseSesK....
.....KsrSrsK....
......KsSsK.....
..f...KwwwK...f.
..fF.KwWhwWK.Ff.
..fg.KWGwGWK.gf.
..f..KwWhwWK..f.
.....KWwwwWK....
.....KWGGwK.....
......KwwK......
.....KxwwK......
.....Kx.xK......
......K.xK......
.........K......
`
    ]
  }),

  // ----- BABY (crawling) -----
  baby: buildSprite({
    w: 16, h: 12,
    palette: {
      '.': null,
      'K': '#1a0a2e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'e': '#180830', 'r': '#ff7070',
      'w': '#ffffff', 'W': '#e8e8e8',
      'b': '#80d0ff', 'B': '#50a0d8', 'D': '#3878a8',
      'p': '#ffb0c0', 'P': '#e080a0',
    },
    frames: [
`
.....Kss.K......
....KseSe.K.....
....KsrSr.K.....
.....KssK.......
....KbBbBbK.....
...KbBDbBDK.....
...KbBbBbK......
....KssKssK.....
....Kx.Kx.K.....
`,
`
.....Kss.K......
....KseSe.K.....
....KsrSr.K.....
.....KssK.......
....KbBbBbK.....
...KbBDbBDK.....
...KbBbBbK......
...KssK.ssK.....
...Kx.K..xK.....
`
    ]
  }),

  // ----- CHILD -----
  child: buildSprite({
    w: 14, h: 18,
    palette: {
      '.': null,
      'K': '#1a0a2e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'e': '#180830', 'r': '#ff7070', 'h': '#402818',
      'w': '#ffffff', 'W': '#e0e0e0',
      'b': '#4060d0', 'B': '#3048a8', 'D': '#203080',
      'n': '#302818', 'N': '#483820',
      't': '#e0c060', 'T': '#c8a040',
    },
    frames: [
`
.....KhhK.....
....KhhhKK....
....KhhhsK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KwKwK....
....KbwKwbK...
....KBbbbBK...
....KbBDbBK...
....KBbbbBK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
....KxKKxK....
....Kx..xK....
`,
`
.....KhhK.....
....KhhhKK....
....KhhhsK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KwKwK....
....KbwKwbK...
....KBbbbBK...
....KbBDbBK...
....KBbbbBK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
....KnNnK.....
....Kx.xK.....
.....K.Kx.....
`
    ]
  }),

  // ----- TEEN -----
  teen: buildSprite({
    w: 14, h: 22,
    palette: {
      '.': null,
      'K': '#1a0a2e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'e': '#180830', 'r': '#ff7070',
      'h': '#301810', 'H': '#482820',
      'w': '#ffffff', 'W': '#e0e0e0',
      'b': '#e04040', 'B': '#b83030', 'D': '#882020',
      'n': '#282848', 'N': '#383860',
      't': '#f0d868', 'T': '#d0b848',
    },
    frames: [
`
.....KhhK.....
....KhHhHK....
....KHhHhK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KtKK.....
....KbKtKbK...
....KBbbbBK...
....KbBDbBK...
....KBbbbBK...
....KDbbbDK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
....KxKKxK....
....Kx..xK....
`,
`
.....KhhK.....
....KhHhHK....
....KHhHhK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KtKK.....
....KbKtKbK...
....KBbbbBK...
....KbBDbBK...
....KBbbbBK...
....KDbbbDK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
....KnNnK.....
....Kx.xK.....
.....K.Kx.....
`
    ]
  }),

  // ----- GRADUATE -----
  grad: buildSprite({
    w: 16, h: 22,
    palette: {
      '.': null,
      'K': '#1a0a2e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'e': '#180830', 'r': '#ff7070',
      'h': '#301810', 'H': '#482820',
      'w': '#ffffff', 'W': '#e0e0e0',
      'b': '#101010', 'B': '#282828', 'D': '#404040',
      'y': '#ffd84d', 'Y': '#e8b830',
      't': '#f8f0d0', 'T': '#d8d0b0',
    },
    frames: [
`
...KBBBBBK......
...KbDbDbK......
....KBBBK.yY....
.....KhhK.......
....KhHhHK......
....KseSesK.....
....KsrSrsK.....
.....KsssK......
....KtTttTK.....
...KtTttTtTK....
...KTtTTtTTK....
...KtTttTtTK....
...KTtTTtTTK....
....KtTtTK......
.....KbBK.......
.....KbBK.......
.....KbBK.......
.....KbBK.......
....KxKKxK......
....Kx..xK......
`,
`
...KBBBBBK......
...KbDbDbK......
....KBBBK.yY....
.....KhhK.......
....KhHhHK......
....KseSesK.....
....KsrSrsK.....
.....KsssK......
....KtTttTK.....
...KtTttTtTK....
...KTtTTtTTK....
...KtTttTtTK....
...KTtTTtTTK....
....KtTtTK......
.....KbBK.......
.....KbBK.......
....KbBbK.......
....Kx.xK.......
.....K.Kx.......
`
    ]
  }),

  // ----- WORKER -----
  worker: buildSprite({
    w: 14, h: 22,
    palette: {
      '.': null,
      'K': '#1a0a2e',
      's': '#ffe0b8', 'S': '#d4a878', 'x': '#b88860',
      'e': '#180830', 'r': '#ff7070',
      'h': '#301810', 'H': '#482820',
      'w': '#ffffff', 'W': '#d8d8d8',
      'b': '#303858', 'B': '#202840', 'D': '#181828',
      'n': '#282838', 'N': '#383848',
      't': '#d03030', 'T': '#a02020',
      'c': '#806040', 'C': '#604830',
    },
    frames: [
`
.....KhhK.....
....KhHhHK....
....KHhHhK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KtTK.....
....KbKtKbK...
...KBbwwwBbK..
...KbBbbbBbK..
...KBbBDBbBK..
...KbBbbbBbK..
....KBbbbBK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
.....KnNK.....
....KxKKxK....
....Kx..xK....
`,
`
.....KhhK.....
....KhHhHK....
....KHhHhK....
....KseSesK...
....KsrSrsK...
.....KsssK....
.....KtTK.....
....KbKtKbK...
...KBbwwwBbK..
...KbBbbbBbK..
...KBbBDBbBK..
...KbBbbbBbK..
....KBbbbBK...
.....KbbK.....
.....KnNK.....
.....KnNK.....
....KnNnK.....
....Kx.xK.....
.....K.Kx.....
`
    ]
  })
};
